// a game in which the user must predict a number generated by a computer
let maxTries = 5;
let counter = 1;
console.log("Welcome user");
let name = (prompt("What is your name?")); // take input from the user
alert(newFunction());

function newFunction() {
    return `Hey, Click 'OK' to start the Game`;
}


function guessNumber() {
    const random = Math.floor(Math.random() * 25 + 1);// generating a random integer from 1 to 25
    let playerGuess = parseInt(prompt('Guess a Number from 0 to 25: '));  // take input from the user
    while (playerGuess !== random && counter < maxTries) { // take the input until Maxtries = 5
        playerGuess = parseInt(prompt("That's not correct! Try again, Pick a Number from 1 to 25: "));
        counter++;
    }

    if (counter >= maxTries) {//when Maxtries is reach
        alert(`You have no more tries left, Press F5 to play again`);
        console.log(`You have no more tries left, Press F5 to play again`);
    }

    // verify if the player's guess is correct.
    if (playerGuess == random) {
        alert("Congratulations!!! You guessed the correct Number:");
        alert("The random number was " + random);
        alert(` It took you ${counter} attempts to guess the correct Number`);
        alert("The game is now finished. Goodbye")
    }

};

// call the function
guessNumber();